### ISSUE TITLE
[Enhancement] Readme should be markdown format

### ISSUE THREAD

**Issue by msigel23** [NoEngineerHere/TeensyELS#18]
Can you please update the ```README``` filename with the markdown extension to ```README.md```. I know you're not an engineer, but it is bugging this software engineer. Cheers.

**Comment by jh247247** [comment]
Yeah I think that was an oversight on my part! Can't remember exactly why I forgot to add the extension :grimacing:

**Comment by jh247247** [comment]
Renamed! Going to close this out :+1:

**Comment by msigel23** [comment]
Sorry, had to do a little bit of trolling with those missing extensions! Awesome project, I love it! 🤙
